// fft2d.cpp — F13 deterministic 2D FFT primitives.
//
// Bit-reproducibility note: the twiddle factors are generated by repeated
// multiplication from a per-stage root of unity computed with std::polar —
// no platform-dependent lookup tables, no threading, no vectorization
// intrinsics that could reorder reductions.
#include "fft2d.h"

#include <cmath>
#include <limits>

namespace sicnu::registration {

namespace {
// M_PI is not portable (MSVC needs _USE_MATH_DEFINES); repo convention is a
// local constant (see topographic_correction.cpp).
constexpr double kPi = 3.14159265358979323846;
} // namespace

bool isPowerOfTwo(std::size_t n) noexcept
{
    return n >= 1 && (n & (n - 1)) == 0;
}

std::size_t nextPowerOfTwo(std::size_t n) noexcept
{
    if (n <= 1)
        return 1;
    // Ceil to the next power of two without UB on overflow.
    std::size_t p = 1;
    while (p < n) {
        if (p > std::numeric_limits<std::size_t>::max() / 2)
            return 0;
        p <<= 1;
    }
    return p;
}

void fft1d(std::vector<std::complex<double>>& a, bool inverse)
{
    const std::size_t n = a.size();
    if (n < 2 || !isPowerOfTwo(n))
        return;

    // Bit-reversal permutation.
    for (std::size_t i = 1, j = 0; i < n; ++i) {
        std::size_t bit = n >> 1;
        for (; j & bit; bit >>= 1)
            j ^= bit;
        j ^= bit;
        if (i < j)
            std::swap(a[i], a[j]);
    }

    const double sign = inverse ? 1.0 : -1.0;
    for (std::size_t len = 2; len <= n; len <<= 1) {
        const double angle = sign * 2.0 * kPi / static_cast<double>(len);
        const std::complex<double> wLen = std::polar(1.0, angle);
        for (std::size_t i = 0; i < n; i += len) {
            std::complex<double> w(1.0, 0.0);
            for (std::size_t k = 0; k < len / 2; ++k) {
                const std::complex<double> u = a[i + k];
                const std::complex<double> v = a[i + k + len / 2] * w;
                a[i + k] = u + v;
                a[i + k + len / 2] = u - v;
                w *= wLen;
            }
        }
    }
}

void fft2d(std::vector<std::complex<double>>& a, std::size_t rows, std::size_t cols, bool inverse)
{
    if (a.size() != rows * cols || rows < 1 || cols < 1)
        return;
    if (!isPowerOfTwo(rows) || !isPowerOfTwo(cols))
        return;

    std::vector<std::complex<double>> row(cols);
    for (std::size_t r = 0; r < rows; ++r) {
        std::copy(a.begin() + static_cast<std::ptrdiff_t>(r * cols),
                  a.begin() + static_cast<std::ptrdiff_t>((r + 1) * cols), row.begin());
        fft1d(row, inverse);
        std::copy(row.begin(), row.end(), a.begin() + static_cast<std::ptrdiff_t>(r * cols));
    }

    std::vector<std::complex<double>> col(rows);
    for (std::size_t c = 0; c < cols; ++c) {
        for (std::size_t r = 0; r < rows; ++r)
            col[r] = a[r * cols + c];
        fft1d(col, inverse);
        for (std::size_t r = 0; r < rows; ++r)
            a[r * cols + c] = col[r];
    }
}

void normalizeInverse2d(std::vector<std::complex<double>>& a, std::size_t rows, std::size_t cols)
{
    const double scale = 1.0 / static_cast<double>(rows * cols);
    for (auto& v : a)
        v *= scale;
}

} // namespace sicnu::registration
