/***************************************************************************
 * diagnostic_catalog.cpp — unified diagnostic lookup implementation
 ***************************************************************************/
#include "help/diagnostic_catalog.h"

namespace sicnu::help
{

DiagnosticCatalog::DiagnosticCatalog( const HelpRegistry &registry )
    : m_registry( registry )
{
}

QString DiagnosticCatalog::idFor( DiagnosticFamily family, const QString &originCode )
{
    return HelpId::diagnosticId( family, originCode );
}

const HelpDescriptor *DiagnosticCatalog::find( DiagnosticFamily family, const QString &originCode ) const
{
    return m_registry.find( idFor( family, originCode ) );
}

HelpDescriptor DiagnosticCatalog::fallback( DiagnosticFamily family, const QString &originCode ) const
{
    HelpDescriptor d;
    d.id = idFor( family, originCode );
    d.kind = HelpKind::Diagnostic;
    d.category = QStringLiteral( "错误与诊断" );
    d.title = originCode;

    DiagnosticInfo info;
    info.originFamily = diagnosticFamilyName( family );
    info.originCode = originCode;
    info.whatHappened =
        QStringLiteral( "系统报告了未收录的诊断代码 %1（family=%2）。" ).arg( originCode, info.originFamily );
    info.whyItMatters =
        QStringLiteral( "尚未为该代码编写专门的处置说明；请结合原始错误消息与所执行的操作判断原因。" );
    info.severity = sicnu::data::DiagnosticSeverity::Error;
    info.retrySense = RetrySense::Manual;
    info.remediation
        << QStringLiteral( "检查输入路径、图层与参数是否与所执行的操作匹配。" )
        << QStringLiteral( "如反复出现，请在日志面板复制完整错误信息（含代码 %1）并反馈。" ).arg( originCode );
    info.technicalNote = QStringLiteral( "fallback descriptor generated by DiagnosticCatalog" );
    d.diagnostic = info;
    d.summary = info.whatHappened.left( 120 );
    return d;
}

HelpDescriptor DiagnosticCatalog::resolve( DiagnosticFamily family, const QString &originCode ) const
{
    if ( const HelpDescriptor *found = find( family, originCode ) )
        return *found;
    return fallback( family, originCode );
}

RetrySense DiagnosticCatalog::retrySenseFromClass( const QString &retryClass )
{
    if ( retryClass == QLatin1String( "none" ) )
        return RetrySense::None;
    if ( retryClass == QLatin1String( "transient" ) )
        return RetrySense::Transient;
    if ( retryClass == QLatin1String( "manual" ) )
        return RetrySense::Manual;
    return RetrySense::Derived;
}

} // namespace sicnu::help
