// tests/test_least_squares.cpp — TDD for QgsLeastSquares (georeferencing)
#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_approx.hpp>

#include "qgsconfig.h"
#include "qgsleastsquares.h"
#include "qgspointxy.h"

#include <QVector>
#include <cmath>

using Catch::Approx;

TEST_CASE("LeastSquares linear: pure translation +100,+200", "[georef][leastsquares]") {
    QVector<QgsPointXY> src = { {0, 0}, {10, 0}, {0, 10}, {10, 10} };
    QVector<QgsPointXY> dst = { {100, 200}, {110, 200}, {100, 210}, {110, 210} };
    QgsPointXY origin;
    double pixelXSize = 0.0;
    double pixelYSize = 0.0;
    QgsLeastSquares::linear(src, dst, origin, pixelXSize, pixelYSize);
    REQUIRE(origin.x() == Approx(100.0).margin(1e-9));
    REQUIRE(origin.y() == Approx(200.0).margin(1e-9));
    REQUIRE(pixelXSize == Approx(1.0).margin(1e-9));
    REQUIRE(pixelYSize == Approx(1.0).margin(1e-9));
}

TEST_CASE("LeastSquares linear: throws SingularException on collinear GCPs", "[georef][leastsquares][error]") {
    // All source points share x=0 (degenerate in x): deltaX = n*sumPx2 - sumPx^2 = 0
    QVector<QgsPointXY> src = { {0, 0}, {0, 1}, {0, 2}, {0, 3} };
    QVector<QgsPointXY> dst = { {0, 0}, {0, 2}, {0, 4}, {0, 6} };
    QgsPointXY origin;
    double pixelXSize = 0.0;
    double pixelYSize = 0.0;
    REQUIRE_THROWS_AS(
        QgsLeastSquares::linear(src, dst, origin, pixelXSize, pixelYSize),
        QgsLeastSquares::SingularException);
}

// --- Helmert / projective need the GSL-backed build (HAVE_GSL, wired in
// CMakeLists.txt); the SICNU-hardened math throws QgsNotSupportedException
// otherwise. Ground truth below is generated by construction: pick transform
// parameters, apply the model to generate correspondences, then verify the
// fit recovers the parameters. ---

namespace {

// Model used by QgsLeastSquares::helmert / QgsHelmertGeorefTransform:
//   dx = a*sx - b*sy + x0 ; dy = b*sx + a*sy + y0
// with a = s*cos(angle), b = s*sin(angle).
QgsPointXY applyHelmert( const QgsPointXY &src, double a, double b, double x0, double y0 )
{
    return QgsPointXY( a * src.x() - b * src.y() + x0,
                       b * src.x() + a * src.y() + y0 );
}

// Applies the row-major 3x3 homography H with a homogeneous divide.
QgsPointXY applyHomography( const QgsPointXY &p, const double H[9] )
{
    const double z = p.x() * H[6] + p.y() * H[7] + H[8];
    return QgsPointXY( ( p.x() * H[0] + p.y() * H[1] + H[2] ) / z,
                       ( p.x() * H[3] + p.y() * H[4] + H[5] ) / z );
}

} // namespace

#ifdef HAVE_GSL
TEST_CASE("LeastSquares helmert: recovers known rotation+uniform-scale+translation", "[georef][leastsquares]") {
    // Ground truth: scale s=2, rotation 30° (=pi/6 rad), translation (-100, +50).
    // a = s*cos(30°) = sqrt(3) ~ 1.7320508, b = s*sin(30°) = 1 exactly.
    const double s = 2.0;
    const double angle = std::acos( -1.0 ) / 6.0; // 30°
    const double a = s * std::cos( angle );
    const double b = s * std::sin( angle );
    const double x0 = -100.0;
    const double y0 = 50.0;

    // 5 well-spread correspondences (overdetermined, but exact data)
    const QVector<QgsPointXY> src = { {10, 20}, {120, 30}, {15, 140}, {130, 150}, {70, 90} };
    QVector<QgsPointXY> dst;
    for ( const QgsPointXY &p : src )
        dst << applyHelmert( p, a, b, x0, y0 );

    QgsPointXY origin;
    double pixelSize = 0.0;
    double rotation = 0.0;
    QgsLeastSquares::helmert( src, dst, origin, pixelSize, rotation );

    REQUIRE( origin.x() == Approx( x0 ).margin( 1e-8 ) );
    REQUIRE( origin.y() == Approx( y0 ).margin( 1e-8 ) );
    REQUIRE( pixelSize == Approx( s ).margin( 1e-8 ) );
    REQUIRE( rotation == Approx( angle ).margin( 1e-9 ) );
}

TEST_CASE("LeastSquares helmert: throws SingularException on degenerate GCPs", "[georef][leastsquares][error]") {
    // All source points identical -> rotation/scale is indistinguishable from
    // translation, the 4x4 normal matrix is singular (rank 2).
    const QVector<QgsPointXY> src = { {5, 5}, {5, 5}, {5, 5}, {5, 5} };
    const QVector<QgsPointXY> dst = { {0, 0}, {10, 10}, {20, 20}, {30, 30} };
    QgsPointXY origin;
    double pixelSize = 0.0;
    double rotation = 0.0;
    REQUIRE_THROWS_AS(
        QgsLeastSquares::helmert( src, dst, origin, pixelSize, rotation ),
        QgsLeastSquares::SingularException );
}

TEST_CASE("LeastSquares projective: recovers known homography", "[georef][leastsquares]") {
    // Ground-truth homography (row-major): anisotropic scale, shear, translation
    // and perspective terms — deliberately not a similarity/affine-only matrix.
    const double H[9] = { 1.5, 0.2, 40.0,
                          0.1, 1.2, -30.0,
                          0.002, 0.001, 1.0 };

    const QVector<QgsPointXY> src = { {0, 0}, {500, 0}, {0, 400}, {500, 400}, {250, 200}, {100, 300} };
    QVector<QgsPointXY> dst;
    for ( const QgsPointXY &p : src )
        dst << applyHomography( p, H );

    double Hfit[9] = {};
    QgsLeastSquares::projective( src, dst, Hfit );

    // The SVD solution is determined up to an arbitrary scale (and sign), so
    // compare transformed coordinates of held-out points instead of raw
    // coefficients — the homogeneous divide cancels the scale.
    const QgsPointXY heldOut[] = { {400, 100}, {-50, 600}, {123, -45} };
    for ( const QgsPointXY &p : heldOut )
    {
        const QgsPointXY expected = applyHomography( p, H );
        const QgsPointXY actual = applyHomography( p, Hfit );
        REQUIRE( actual.x() == Approx( expected.x() ).margin( 1e-6 ) );
        REQUIRE( actual.y() == Approx( expected.y() ).margin( 1e-6 ) );
    }
}

TEST_CASE("LeastSquares projective: degenerate input handling", "[georef][leastsquares][error]") {
    double H[9] = {};

    // Too few correspondences (n < 4)
    const QVector<QgsPointXY> src3 = { {0, 0}, {10, 0}, {0, 10} };
    const QVector<QgsPointXY> dst3 = { {1, 1}, {11, 1}, {1, 11} };
    REQUIRE_THROWS_AS( QgsLeastSquares::projective( src3, dst3, H ), std::domain_error );

    // All points identical -> coordinate normalization degenerates (meanDist ~ 0)
    const QVector<QgsPointXY> srcIdent = { {7, 7}, {7, 7}, {7, 7}, {7, 7} };
    const QVector<QgsPointXY> dstIdent = { {1, 1}, {2, 2}, {3, 3}, {4, 4} };
    REQUIRE_THROWS_AS( QgsLeastSquares::projective( srcIdent, dstIdent, H ),
                       QgsLeastSquares::SingularException );
}
#endif
