// tests/test_gcp_transformer.cpp — TDD for QgsGcpTransformerInterface
#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_approx.hpp>

#include "qgsgcptransformer.h"
#include "qgspointxy.h"

#include <QVector>
#include <cmath>
#include <memory>

using Catch::Approx;
using TM = QgsGcpTransformerInterface::TransformMethod;

namespace {
struct GcpPair {
    double sx, sy, dx, dy;
};

QVector<QgsPointXY> sources( const std::vector<GcpPair> &g ) {
    QVector<QgsPointXY> r;
    r.reserve( static_cast<int>( g.size() ) );
    for ( const auto &p : g )
        r.emplace_back( p.sx, p.sy );
    return r;
}

QVector<QgsPointXY> destinations( const std::vector<GcpPair> &g ) {
    QVector<QgsPointXY> r;
    r.reserve( static_cast<int>( g.size() ) );
    for ( const auto &p : g )
        r.emplace_back( p.dx, p.dy );
    return r;
}

int minimumGcpCountFor( TM method ) {
    std::unique_ptr<QgsGcpTransformerInterface> t( QgsGcpTransformerInterface::create( method ) );
    REQUIRE( t != nullptr );
    return t->minimumGcpCount();
}

// Model used by QgsHelmertGeorefTransform:
//   dx = a*sx - b*sy + x0 ; dy = b*sx + a*sy + y0
// with a = s*cos(angle), b = s*sin(angle).
QgsPointXY applyHelmert( const QgsPointXY &src, double a, double b, double x0, double y0 ) {
    return QgsPointXY( a * src.x() - b * src.y() + x0,
                       b * src.x() + a * src.y() + y0 );
}

// Row-major 3x3 homography application with a homogeneous divide.
QgsPointXY applyHomography( const QgsPointXY &p, const double H[9] ) {
    const double z = p.x() * H[6] + p.y() * H[7] + H[8];
    return QgsPointXY( ( p.x() * H[0] + p.y() * H[1] + H[2] ) / z,
                       ( p.x() * H[3] + p.y() * H[4] + H[5] ) / z );
}
} // namespace

TEST_CASE( "minimumGcpCount per method", "[georef][transformer]" ) {
    REQUIRE( minimumGcpCountFor( TM::Linear ) == 2 );
    REQUIRE( minimumGcpCountFor( TM::Helmert ) == 2 );
    REQUIRE( minimumGcpCountFor( TM::PolynomialOrder1 ) == 3 );
    REQUIRE( minimumGcpCountFor( TM::PolynomialOrder2 ) == 6 );
    REQUIRE( minimumGcpCountFor( TM::PolynomialOrder3 ) == 10 );
    REQUIRE( minimumGcpCountFor( TM::ThinPlateSpline ) == 1 );
    REQUIRE( minimumGcpCountFor( TM::Projective ) == 4 );
}

TEST_CASE( "PolynomialOrder1: pure translation roundtrip", "[georef][transformer]" ) {
    // Source -> destination with +100,+200 offset
    std::vector<GcpPair> g = {
        { 0, 0, 100, 200 },
        { 10, 0, 110, 200 },
        { 0, 10, 100, 210 }
    };
    std::unique_ptr<QgsGcpTransformerInterface> t(
        QgsGcpTransformerInterface::createFromParameters( TM::PolynomialOrder1, sources( g ), destinations( g ) ) );
    REQUIRE( t != nullptr );

    double x = 5.0;
    double y = 5.0;
    REQUIRE( t->transform( x, y, false ) );
    REQUIRE( x == Approx( 105.0 ).margin( 1e-6 ) );
    REQUIRE( y == Approx( 205.0 ).margin( 1e-6 ) );
}

TEST_CASE( "Linear transform: pure translation", "[georef][transformer]" ) {
    // Linear (scale + translation) — exercise the codepath that does not require GSL
    std::vector<GcpPair> g = {
        { 0, 0, 100, 200 },
        { 10, 0, 110, 200 },
        { 0, 10, 100, 210 },
        { 10, 10, 110, 210 }
    };
    std::unique_ptr<QgsGcpTransformerInterface> t(
        QgsGcpTransformerInterface::createFromParameters( TM::Linear, sources( g ), destinations( g ) ) );
    REQUIRE( t != nullptr );

    double x = 5.0;
    double y = 5.0;
    REQUIRE( t->transform( x, y, false ) );
    REQUIRE( x == Approx( 105.0 ).margin( 1e-6 ) );
    REQUIRE( y == Approx( 205.0 ).margin( 1e-6 ) );
}

// --- Helmert / projective round-trips. These exercise the GSL-backed
// QgsLeastSquares fit (HAVE_GSL wired in CMakeLists.txt); ground truth is
// generated by construction from known transform parameters, and the
// upstream-literal cases carry independently verified QGIS expectations. ---

TEST_CASE( "Helmert: known rotation+scale+translation roundtrip", "[georef][transformer]" ) {
    // Ground truth: scale s=2, rotation 30° (=pi/6 rad), translation (-100, +50).
    // a = s*cos(30°) = sqrt(3), b = s*sin(30°) = 1 exactly.
    const double s = 2.0;
    const double angle = std::acos( -1.0 ) / 6.0;
    const double a = s * std::cos( angle );
    const double b = s * std::sin( angle );
    const double x0 = -100.0;
    const double y0 = 50.0;

    const QVector<QgsPointXY> src = { {10, 20}, {120, 30}, {15, 140}, {130, 150}, {70, 90} };
    QVector<QgsPointXY> dst;
    for ( const QgsPointXY &p : src )
        dst << applyHelmert( p, a, b, x0, y0 );

    std::unique_ptr<QgsGcpTransformerInterface> t(
        QgsGcpTransformerInterface::createFromParameters( TM::Helmert, src, dst ) );
    REQUIRE( t != nullptr );

    // Held-out point transformed to its by-construction destination and back
    const QgsPointXY heldOut( 60, 90 );
    const QgsPointXY expected = applyHelmert( heldOut, a, b, x0, y0 );
    double x = heldOut.x();
    double y = heldOut.y();
    REQUIRE( t->transform( x, y, false ) );
    REQUIRE( x == Approx( expected.x() ).margin( 1e-6 ) );
    REQUIRE( y == Approx( expected.y() ).margin( 1e-6 ) );
    REQUIRE( t->transform( x, y, true ) );
    REQUIRE( x == Approx( heldOut.x() ).margin( 1e-6 ) );
    REQUIRE( y == Approx( heldOut.y() ).margin( 1e-6 ) );
}

TEST_CASE( "Helmert: upstream GCP set matches QGIS reference values", "[georef][transformer]" ) {
    // Ported from refs/qgis/tests/src/analysis/testqgsgcptransformer.cpp
    // (testHelmert): expected outputs are upstream-verified literals.
    std::vector<GcpPair> g = {
        { 288, 1126, 321210, 130280 },
        { 2352, 716, 322698, 129979 },
        { 2067, 2398, 322501, 192061 },
        { 1102, 2209, 321803, 192198 }
    };
    std::unique_ptr<QgsGcpTransformerInterface> t(
        QgsGcpTransformerInterface::createFromParameters( TM::Helmert, sources( g ), destinations( g ) ) );
    REQUIRE( t != nullptr );

    double x = 288.0;
    double y = 1000.0;
    REQUIRE( t->transform( x, y, false ) );
    REQUIRE( x == Approx( 302325.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( 145676.0 ).margin( 1.0 ) );
    REQUIRE( t->transform( x, y, true ) );
    REQUIRE( x == Approx( 288.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( 1000.0 ).margin( 1.0 ) );

    x = 2352.0;
    y = 1150.0;
    REQUIRE( t->transform( x, y, false ) );
    REQUIRE( x == Approx( 340495.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( 155540.0 ).margin( 1.0 ) );
    REQUIRE( t->transform( x, y, true ) );
    REQUIRE( x == Approx( 2352.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( 1150.0 ).margin( 1.0 ) );
}

TEST_CASE( "Helmert invertYAxis: upstream raster-y set matches QGIS reference values", "[georef][transformer]" ) {
    // Ported from testqgsgcptransformer.cpp (testHelmertRasterYAxis): source
    // coordinates use the raster top-to-bottom y convention and the fit runs
    // with invertYAxis=true; the forward transform flips the rotation sign.
    std::vector<GcpPair> g = {
        { 288, -716, 321210, 130280 },
        { 2352, -1126, 322698, 129979 },
        { 2067, -2398, 322501, 192061 },
        { 1102, -2209, 321803, 192198 }
    };
    QgsHelmertGeorefTransform raw;
    REQUIRE( raw.updateParametersFromGcps( sources( g ), destinations( g ), true ) );

    double x = 288.0;
    double y = -716.0;
    REQUIRE( raw.transform( x, y, false ) );
    REQUIRE( x == Approx( 334590.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( 115324.0 ).margin( 1.0 ) );
    REQUIRE( raw.transform( x, y, true ) );
    REQUIRE( x == Approx( 288.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( -716.0 ).margin( 1.0 ) );

    x = 2352.0;
    y = -1126.0;
    REQUIRE( raw.transform( x, y, false ) );
    REQUIRE( x == Approx( 296200.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( 115340.0 ).margin( 1.0 ) );
    REQUIRE( raw.transform( x, y, true ) );
    REQUIRE( x == Approx( 2352.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( -1126.0 ).margin( 1.0 ) );
}

TEST_CASE( "Projective: known homography roundtrip", "[georef][transformer]" ) {
    // Ground-truth homography (row-major): anisotropic scale, shear, translation
    // and perspective terms — deliberately not affine-only.
    const double H[9] = { 1.5, 0.2, 40.0,
                          0.1, 1.2, -30.0,
                          0.002, 0.001, 1.0 };

    const QVector<QgsPointXY> src = { {0, 0}, {500, 0}, {0, 400}, {500, 400}, {250, 200}, {100, 300} };
    QVector<QgsPointXY> dst;
    for ( const QgsPointXY &p : src )
        dst << applyHomography( p, H );

    std::unique_ptr<QgsGcpTransformerInterface> t(
        QgsGcpTransformerInterface::createFromParameters( TM::Projective, src, dst ) );
    REQUIRE( t != nullptr );

    // Held-out point transformed to its by-construction destination and back
    const QgsPointXY heldOut( 400, 100 );
    const QgsPointXY expected = applyHomography( heldOut, H );
    double x = heldOut.x();
    double y = heldOut.y();
    REQUIRE( t->transform( x, y, false ) );
    REQUIRE( x == Approx( expected.x() ).margin( 1e-6 ) );
    REQUIRE( y == Approx( expected.y() ).margin( 1e-6 ) );
    REQUIRE( t->transform( x, y, true ) );
    REQUIRE( x == Approx( heldOut.x() ).margin( 1e-6 ) );
    REQUIRE( y == Approx( heldOut.y() ).margin( 1e-6 ) );
}

TEST_CASE( "Projective: upstream 4-GCP set matches QGIS reference values", "[georef][transformer]" ) {
    // Ported from testqgsgcptransformer.cpp (testProjective): exactly 4 GCPs,
    // which exercises the SVD duplicate-last-row path for a 9x9 system.
    std::vector<GcpPair> g = {
        { 288, 1126, 321210, 130280 },
        { 2352, 716, 322698, 129979 },
        { 2067, 2398, 322501, 192061 },
        { 1102, 2209, 321803, 192198 }
    };
    std::unique_ptr<QgsGcpTransformerInterface> t(
        QgsGcpTransformerInterface::createFromParameters( TM::Projective, sources( g ), destinations( g ) ) );
    REQUIRE( t != nullptr );

    double x = 288.0;
    double y = 1000.0;
    REQUIRE( t->transform( x, y, false ) );
    REQUIRE( x == Approx( 321256.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( 123764.0 ).margin( 1.0 ) );
    REQUIRE( t->transform( x, y, true ) );
    REQUIRE( x == Approx( 288.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( 1000.0 ).margin( 1.0 ) );

    x = 2352.0;
    y = 1150.0;
    REQUIRE( t->transform( x, y, false ) );
    REQUIRE( x == Approx( 322687.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( 142908.0 ).margin( 1.0 ) );
    REQUIRE( t->transform( x, y, true ) );
    REQUIRE( x == Approx( 2352.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( 1150.0 ).margin( 1.0 ) );
}

TEST_CASE( "Projective invertYAxis: upstream raster-y set matches QGIS reference values", "[georef][transformer]" ) {
    // Ported from testqgsgcptransformer.cpp (testProjectiveRasterYAxis): with
    // invertYAxis=true the source y coordinates are flipped before the fit.
    std::vector<GcpPair> g = {
        { 288, -716, 321210, 130280 },
        { 2352, -1126, 322698, 129979 },
        { 2067, -2398, 322501, 192061 },
        { 1102, -2209, 321803, 192198 }
    };
    QgsProjectiveGeorefTransform raw;
    REQUIRE( raw.updateParametersFromGcps( sources( g ), destinations( g ), true ) );

    double x = 288.0;
    double y = -716.0;
    REQUIRE( raw.transform( x, y, false ) );
    REQUIRE( x == Approx( 321203.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( 63965.0 ).margin( 1.0 ) );
    REQUIRE( raw.transform( x, y, true ) );
    REQUIRE( x == Approx( 288.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( -716.0 ).margin( 1.0 ) );

    x = 2352.0;
    y = -1126.0;
    REQUIRE( raw.transform( x, y, false ) );
    REQUIRE( x == Approx( 322681.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( 25366.0 ).margin( 1.0 ) );
    REQUIRE( raw.transform( x, y, true ) );
    REQUIRE( x == Approx( 2352.0 ).margin( 1.0 ) );
    REQUIRE( y == Approx( -1126.0 ).margin( 1.0 ) );
}

TEST_CASE( "GCP transformer: returns false / nullptr on singular GCP inputs without throwing", "[georef][transformer][error]" ) {
    const QVector<QgsPointXY> collinearSrc = { {0, 0}, {10, 0}, {20, 0}, {30, 0} };
    const QVector<QgsPointXY> collinearDst = { {100, 200}, {110, 200}, {120, 200}, {130, 200} };

    // Linear
    QgsLinearGeorefTransform linear;
    CHECK_FALSE( linear.updateParametersFromGcps( collinearSrc, collinearDst ) );
    CHECK( QgsGcpTransformerInterface::createFromParameters( TM::Linear, collinearSrc, collinearDst ) == nullptr );

    // Helmert
    const QVector<QgsPointXY> identicalSrc = { {5, 5}, {5, 5}, {5, 5}, {5, 5} };
    QgsHelmertGeorefTransform helmert;
    CHECK_FALSE( helmert.updateParametersFromGcps( identicalSrc, collinearDst ) );
    CHECK( QgsGcpTransformerInterface::createFromParameters( TM::Helmert, identicalSrc, collinearDst ) == nullptr );

    // Projective
    QgsProjectiveGeorefTransform proj;
    CHECK_FALSE( proj.updateParametersFromGcps( collinearSrc, collinearDst ) );
    CHECK( QgsGcpTransformerInterface::createFromParameters( TM::Projective, collinearSrc, collinearDst ) == nullptr );
}

#include "qgsgcppoint.h"
#include "qgscoordinatereferencesystem.h"
#include "qgscoordinatetransformcontext.h"

TEST_CASE( "GcpPoint: transformedDestinationPoint surfaces ok status", "[georef][gcp]" ) {
    QgsCoordinateReferenceSystem wgs84( "EPSG:4326" );
    QgsCoordinateReferenceSystem utm( "EPSG:32633" );
    QgsCoordinateTransformContext ctx;

    QgsGcpPoint pt( QgsPointXY( 10, 20 ), QgsPointXY( 12.0, 55.0 ), wgs84 );
    bool ok = false;
    QgsPointXY dst = pt.transformedDestinationPoint( utm, ctx, &ok );
    CHECK( ok );
    CHECK( dst.x() > 100000.0 );
    CHECK( dst.y() > 1000000.0 );

    // Invalid target CRS returns original point and sets ok = true (noop)
    QgsCoordinateReferenceSystem invalidCrs;
    QgsPointXY noop = pt.transformedDestinationPoint( invalidCrs, ctx, &ok );
    CHECK( ok );
    CHECK( noop.x() == 12.0 );
    CHECK( noop.y() == 55.0 );
}
