/***************************************************************************
 * tests/test_lab_batch_classroom_safety.cpp — classroom-safety 13.0 gates
 *
 * Three properties the batch grader must hold before a teacher opens a
 * grades CSV:
 *
 *   1. formula injection — a cell whose first character is = + - @ TAB CR is
 *      neutralized with a leading apostrophe, exactly like csv_safe() in
 *      scripts/run_classroom_batch.py. Student ids and deduction texts are
 *      attacker-controlled in the classroom threat model.
 *   2. typed unavailable — a submission that cannot be graded (missing
 *      capability / fixture / rules / artifact) reports verdict
 *      "unavailable" with a reason and NO score. Never a fabricated zero.
 *   3. course scale — row count is invariant, the JSON summary is
 *      deterministic, and nothing reaches the network.
 *
 * The CSV injection corpus is shared with the Python reference
 * implementation through tests/data/csv_injection_golden.json (generated by
 * scripts/gen_csv_golden.py). The two code paths are different
 * implementations; this lane is what keeps them from drifting apart.
 ***************************************************************************/

#include "cli/lab_batch_runner.h"

#include <QDir>
#include <QFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QTemporaryDir>

#include <catch2/catch_test_macros.hpp>

#include <string>
#include <vector>
#include <QJsonArray>
#include <QJsonValue>

namespace
{

QString repoRoot()
{
#ifdef CMAKE_SOURCE_DIR
  return QStringLiteral( CMAKE_SOURCE_DIR );
#else
  return QStringLiteral( "." );
#endif
}

/// Every dangerous first character the classroom threat model cares about,
/// plus the counter-examples that must NOT be touched.
const std::vector<std::string> &dangerousFirstChars()
{
  static const std::vector<std::string> chars = { "=", "+", "-", "@", "\t", "\r" };
  return chars;
}

sicnu::agent::OutputVerifier::LabGradeResult gradedResult( double score )
{
  sicnu::agent::OutputVerifier::LabGradeResult result;
  result.graded = true;
  result.score = score;
  result.verdict = score >= 60.0 ? QStringLiteral( "pass" ) : QStringLiteral( "fail" );
  return result;
}

sicnu::agent::OutputVerifier::LabGradeResult unavailableResult( const QString &reason )
{
  sicnu::agent::OutputVerifier::LabGradeResult result;
  result.graded = false;
  result.verdict = QStringLiteral( "unavailable" );
  result.error = reason;
  return result;
}

bool writeFile( const QString &path, const QByteArray &body )
{
  QFile file( path );
  if ( !file.open( QIODevice::WriteOnly ) )
    return false;
  return file.write( body ) == body.size();
}

QByteArray readFile( const QString &path )
{
  QFile file( path );
  if ( !file.open( QIODevice::ReadOnly ) )
    return QByteArray();
  return file.readAll();
}

/// QTemporaryDir::path() is the directory itself; kept as a named helper so
/// every output path in this file is visibly outside the submissions dir.
QString outDirPath( const QTemporaryDir &dir )
{
  return dir.path();
}

QString makeSubmission( const QDir &dir, const QString &fileName, const QByteArray &body )
{
  const QString path = dir.absoluteFilePath( fileName );
  REQUIRE( writeFile( path, body ) );
  return path;
}

} // namespace

TEST_CASE( "csvSafeCell neutralizes every spreadsheet-formula first character",
           "[csv][formula-injection]" )
{
  using sicnu::cli::csvSafeCell;

  for ( const std::string &lead : dangerousFirstChars() )
  {
    const QString input = QString::fromStdString( lead + std::string( "payload" ) );
    const QString output = csvSafeCell( input );
    UNSCOPED_INFO( "leading byte " << static_cast<int>( lead[0] ) );
    REQUIRE( output == QString( QLatin1Char( '\'' ) ) + input );
    REQUIRE( output.at( 0 ) == QLatin1Char( '\'' ) );
  }

  // A real-world payload: the apostrophe must land in front of the '='.
  REQUIRE( csvSafeCell( QStringLiteral( "=cmd|'/c calc'!A1" ) ) ==
           QStringLiteral( "'=cmd|'/c calc'!A1" ) );

  // Counter-examples: nothing else may be rewritten.
  REQUIRE( csvSafeCell( QString() ) == QString() );
  REQUIRE( csvSafeCell( QStringLiteral( "2024001" ) ) == QStringLiteral( "2024001" ) );
  REQUIRE( csvSafeCell( QStringLiteral( "a=b" ) ) == QStringLiteral( "a=b" ) );
  REQUIRE( csvSafeCell( QStringLiteral( "张=三" ) ) == QStringLiteral( "张=三" ) );
  REQUIRE( csvSafeCell( QStringLiteral( "  =lead" ) ) == QStringLiteral( "  =lead" ) );
  REQUIRE( csvSafeCell( QStringLiteral( "\n=x" ) ) == QStringLiteral( "\n=x" ) );
}

TEST_CASE( "the C++ neutralizer agrees with the Python reference implementation",
           "[csv][formula-injection][parity]" )
{
  const QString goldenPath = repoRoot() + QStringLiteral( "/tests/data/csv_injection_golden.json" );
  const QByteArray raw = readFile( goldenPath );
  REQUIRE( !raw.isEmpty() ); // a missing corpus is a red gate, never a skip

  const QJsonDocument doc = QJsonDocument::fromJson( raw );
  REQUIRE( doc.isObject() );
  const QJsonArray cases = doc.object().value( QStringLiteral( "cases" ) ).toArray();
  REQUIRE( cases.size() >= 8 );

  int checked = 0;
  for ( const QJsonValue &entry : cases )
  {
    REQUIRE( entry.isObject() );
    const QString input = entry.toObject().value( QStringLiteral( "input" ) ).toString();
    const QString expected = entry.toObject().value( QStringLiteral( "output" ) ).toString();
    UNSCOPED_INFO( "case: " << input.toStdString() );
    REQUIRE( sicnu::cli::csvSafeCell( input ) == expected );
    ++checked;
  }
  REQUIRE( checked == cases.size() );
}

TEST_CASE( "a batch CSV neutralizes attacker-controlled cells on disk",
           "[csv][formula-injection]" )
{
  QTemporaryDir temp;
  REQUIRE( temp.isValid() );
  const QDir dir( temp.path() );

  // Student id = file stem, so the file name IS the injection vector.
  makeSubmission( dir, QStringLiteral( "=evil_calc.tif" ), QByteArray( "AAAA" ) );
  makeSubmission( dir, QStringLiteral( "+sum_student.tif" ), QByteArray( "BBBB" ) );
  makeSubmission( dir, QStringLiteral( "normal_student.tif" ), QByteArray( "CCCC" ) );

  const QString csvPath = dir.absoluteFilePath( QStringLiteral( "grades.csv" ) );
  sicnu::cli::LabBatchOptions options;
  options.jsonPath = dir.absoluteFilePath( QStringLiteral( "summary.json" ) );

  const sicnu::cli::LabBatchSummary summary = sicnu::cli::LabBatchRunner::run(
    temp.path(), QStringLiteral( "@lab12_sar_processing" ), csvPath,
    []( const QString & ) { return gradedResult( 100.0 ); }, options );

  REQUIRE( summary.usageError == false );
  REQUIRE( summary.rows.size() == 3 );

  const QByteArray csv = readFile( csvPath );
  REQUIRE( csv.startsWith( "\xEF\xBB\xBF" ) ); // UTF-8 BOM
  const QString text = QString::fromUtf8( csv );
  REQUIRE( text.contains( QStringLiteral( "student_id,lab_id,score,verdict,top_deduction,"
                                          "artifact_path\r\n" ) ) );

  // Every neutralized cell appears quoted-or-bare but always apostrophe-first.
  REQUIRE( text.contains( QStringLiteral( "'=evil_calc" ) ) );
  REQUIRE( text.contains( QStringLiteral( "'+sum_student" ) ) );
  REQUIRE( text.contains( QStringLiteral( "'@lab12_sar_processing" ) ) );
  // The untouched student keeps its exact id.
  REQUIRE( text.contains( QStringLiteral( "normal_student" ) ) );
  // No un-neutralized formula survives at the start of any field.
  REQUIRE( !text.contains( QStringLiteral( ",=evil_calc" ) ) );
  REQUIRE( !text.contains( QStringLiteral( ",+sum_student" ) ) );

  // Canonical truth is NOT neutralized — the JSON keeps the real id.
  const QByteArray jsonRaw = readFile( options.jsonPath );
  REQUIRE( !jsonRaw.isEmpty() );
  const QJsonObject body = QJsonDocument::fromJson( jsonRaw ).object();
  REQUIRE( body.value( QStringLiteral( "lab_id" ) ).toString() ==
           QStringLiteral( "@lab12_sar_processing" ) );
  const QJsonArray rows = body.value( QStringLiteral( "rows" ) ).toArray();
  REQUIRE( rows.size() == 3 );
  bool sawEvil = false;
  for ( const QJsonValue &row : rows )
  {
    const QString id = row.toObject().value( QStringLiteral( "student_id" ) ).toString();
    if ( id == QStringLiteral( "=evil_calc" ) )
      sawEvil = true;
  }
  REQUIRE( sawEvil );
}

TEST_CASE( "an ungradeable submission is reported unavailable, never as zero",
           "[unavailable]" )
{
  QTemporaryDir temp;
  REQUIRE( temp.isValid() );
  const QDir dir( temp.path() );
  makeSubmission( dir, QStringLiteral( "student_a.tif" ), QByteArray( "AAAA" ) );

  const QString csvPath = dir.absoluteFilePath( QStringLiteral( "grades.csv" ) );
  sicnu::cli::LabBatchOptions options;
  options.jsonPath = dir.absoluteFilePath( QStringLiteral( "summary.json" ) );

  const sicnu::cli::LabBatchSummary summary = sicnu::cli::LabBatchRunner::run(
    temp.path(), QStringLiteral( "lab13_hyperspectral_analysis" ), csvPath,
    []( const QString & )
    { return unavailableResult( QStringLiteral( "capability rs:mnf is not shipped in this bundle" ) ); },
    options );

  REQUIRE( summary.unavailable == 1 );
  REQUIRE( summary.isolated == 0 );   // a typed refusal is not a crash
  REQUIRE( summary.graded == 0 );
  REQUIRE( summary.rows.size() == 1 ); // row-count invariant holds

  const sicnu::cli::LabBatchRow &row = summary.rows.at( 0 );
  REQUIRE( row.unavailable );
  REQUIRE( row.score < 0.0 );                    // no score at all
  REQUIRE( row.verdict == QStringLiteral( "unavailable" ) );
  REQUIRE( row.unavailableReason ==
           QStringLiteral( "capability rs:mnf is not shipped in this bundle" ) );

  const QJsonObject body = QJsonDocument::fromJson( readFile( options.jsonPath ) ).object();
  const QJsonObject entry = body.value( QStringLiteral( "rows" ) ).toArray().at( 0 ).toObject();
  REQUIRE( entry.value( QStringLiteral( "unavailable" ) ).toBool() );
  REQUIRE( entry.value( QStringLiteral( "unavailable_reason" ) ).toString() ==
           QStringLiteral( "capability rs:mnf is not shipped in this bundle" ) );
  REQUIRE( !entry.contains( QStringLiteral( "score" ) ) );
  REQUIRE( body.value( QStringLiteral( "unavailable" ) ).toInt() == 1 );

  // A class nobody could grade must not look like a success.
  REQUIRE( sicnu::cli::batchExitCodeFor( summary ) != 0 );

  // The CSV still carries exactly one row, with an empty score column.
  const QString text = QString::fromUtf8( readFile( csvPath ) );
  REQUIRE( text.contains( QStringLiteral( "student_a,lab13_hyperspectral_analysis,,unavailable" ) ) );
}

TEST_CASE( "course-scale batch: row count invariant, deterministic, offline",
           "[course-scale]" )
{
  QTemporaryDir temp;
  REQUIRE( temp.isValid() );
  const QDir dir( temp.path() );

  const int kSubmissions = 24;
  for ( int i = 0; i < kSubmissions; ++i )
  {
    const QString name = QStringLiteral( "s%1.tif" ).arg( i, 2, 10, QLatin1Char( '0' ) );
    makeSubmission( dir, name, QByteArray( 16 + i, static_cast<char>( 'A' + ( i % 26 ) ) ) );
  }

  // Outputs live OUTSIDE the submissions directory: the runner excludes only
  // the outputs of the run it is performing, so a summary written next to the
  // submissions would be graded as a submission on the next pass.
  QTemporaryDir out;
  REQUIRE( out.isValid() );
  const QString outDir = outDirPath( out );
  const QString csvPath = outDir + QStringLiteral( "/grades.csv" );
  const QString jsonPath = outDir + QStringLiteral( "/summary.json" );
  sicnu::cli::LabBatchOptions options;
  options.jsonPath = jsonPath;

  // One lab's rules are malformed (grader throws), one lab cannot be graded
  // here (typed unavailable), the rest grade normally.
  const auto grade = []( const QString &artifact ) -> sicnu::agent::OutputVerifier::LabGradeResult
  {
    const QString base = QFileInfo( artifact ).completeBaseName();
    if ( base == QStringLiteral( "s03" ) )
      throw std::runtime_error( "malformed rules: expected object at assertions[2]" );
    if ( base == QStringLiteral( "s07" ) )
      return unavailableResult( QStringLiteral( "fixture data/labs/_tmp/sar is absent offline" ) );
    return gradedResult( base == QStringLiteral( "s11" ) ? 12.0 : 88.0 );
  };

  const sicnu::cli::LabBatchSummary summary = sicnu::cli::LabBatchRunner::run(
    temp.path(), QStringLiteral( "lab12_sar_processing" ), csvPath, grade, options );

  REQUIRE( summary.total == kSubmissions );
  REQUIRE( summary.rows.size() == kSubmissions ); // row-count invariant
  REQUIRE( summary.isolated == 1 );               // s03 threw
  REQUIRE( summary.unavailable == 1 );            // s07 typed refusal
  REQUIRE( summary.graded == kSubmissions - 2 );

  const QByteArray first = readFile( jsonPath );
  REQUIRE( !first.isEmpty() );

  // Determinism: a second run over the same corpus is byte-identical. The
  // outputs live in a SEPARATE directory on purpose: the runner excludes only
  // the outputs of the run it is performing, so writing summaries next to the
  // submissions would make the next run grade grades.csv as a submission.
  const QString csv1 = outDir + QStringLiteral( "/grades1.csv" );
  const QString json1 = outDir + QStringLiteral( "/summary1.json" );
  sicnu::cli::LabBatchOptions options1;
  options1.jsonPath = json1;
  const sicnu::cli::LabBatchSummary rerunA = sicnu::cli::LabBatchRunner::run(
    temp.path(), QStringLiteral( "lab12_sar_processing" ), csv1, grade, options1 );

  const QString csv2 = outDir + QStringLiteral( "/grades2.csv" );
  const QString json2 = outDir + QStringLiteral( "/summary2.json" );
  sicnu::cli::LabBatchOptions options2;
  options2.jsonPath = json2;
  const sicnu::cli::LabBatchSummary rerunB = sicnu::cli::LabBatchRunner::run(
    temp.path(), QStringLiteral( "lab12_sar_processing" ), csv2, grade, options2 );

  REQUIRE( rerunA.rows.size() == kSubmissions );
  REQUIRE( rerunB.rows.size() == rerunA.rows.size() );
  REQUIRE( readFile( json2 ) == readFile( json1 ) );
  REQUIRE( readFile( csv2 ) == readFile( csv1 ) );

  // Offline: no remote scheme ever appears in the canonical summary.
  const QString jsonText = QString::fromUtf8( first );
  REQUIRE( !jsonText.contains( QStringLiteral( "http://" ) ) );
  REQUIRE( !jsonText.contains( QStringLiteral( "https://" ) ) );
  REQUIRE( !jsonText.contains( QStringLiteral( "ftp://" ) ) );

  // Bounded: the cap stops the run and still reports it.
  sicnu::cli::LabBatchOptions capped;
  capped.maxSubmissions = 5;
  const sicnu::cli::LabBatchSummary cappedSummary = sicnu::cli::LabBatchRunner::run(
    temp.path(), QStringLiteral( "lab12_sar_processing" ),
    outDir + QStringLiteral( "/capped.csv" ), grade, capped );
  REQUIRE( cappedSummary.cappedByMaxSubmissions );
  REQUIRE( cappedSummary.rows.size() == 5 );
  REQUIRE( sicnu::cli::batchExitCodeFor( cappedSummary ) != 0 );

  // Cooperative cancellation (the in-process form of a grading deadline).
  int seen = 0;
  sicnu::cli::LabBatchOptions stopping;
  stopping.cancelled = [&seen]() { return ++seen > 3; };
  const sicnu::cli::LabBatchSummary stopped = sicnu::cli::LabBatchRunner::run(
    temp.path(), QStringLiteral( "lab12_sar_processing" ),
    outDir + QStringLiteral( "/stopped.csv" ), grade, stopping );
  REQUIRE( stopped.cancelled );
  REQUIRE( stopped.rows.size() < kSubmissions );
  REQUIRE( sicnu::cli::batchExitCodeFor( stopped ) != 0 );
}
