// main_window_docks.cpp — Dock widget setup
// Extracted from main_window.cpp for maintainability
#include "main_window.h"

#include "active_view_host.h"
#include "log_panel.h"
#include "panels/data_manager_panel.h"
#include "panels/workspace_browser_panel.h"
#include "project_context.h"
#include "data/data_asset.h"
#include "data/data_manager.h"
#include "processing/framework/json_params_converter.h"
#include "processing/framework/task_center.h"
#include "shell/processing_job_adapter.h"
#include "shell/ribbon_controller.h"
#include "shell/rs_job_panel.h"
#include "shell/task_panel_host.h"
#include "shell/workflow_session_controller.h"
#include "workflow/pipeline_editor_dock.h"
#include "workflow/workflow_definition.h"
#include "agent/agent_copilot_dock_widget.h"
#include "agent/workspace_state.h"
#include "widgets/spectral_profile_widget.h"
#include "widgets/spectral_workbench_panel.h"
#include "widgets/guided_workflow_widget.h"
#include "teaching/lab_cockpit_dock.h"
#include "teaching_admin/teaching_admin_dock.h"
