# LEGACY (BUILD-12): not added via add_subdirectory() in the main build; references
# undefined WITH_DESKTOP/QGIS_DATA_DIR. Retained for reference only.
########################################################
# Files


########################################################
# Build


########################################################
# Continue on to subdirs
add_subdirectory(icons)
add_subdirectory(themes)
add_subdirectory(svg)
