#!/usr/bin/env python3
"""gen_lab_docs.py — render docs/labs/*.md and docs/labs/README.md from LabSpec.

The JSON files under data/labs/ are the single source of truth for lab
exercises (ADR 0146); the markdown under docs/labs/ is build output. Never
hand-edit the generated files — edit the LabSpec and re-run:

    python3 scripts/gen_lab_docs.py            # regenerate in place
    python3 scripts/gen_lab_docs.py --check    # exit 1 if committed docs differ

Output is deterministic: labs render in file-name order, step tables render in
document order, no timestamps or locale-dependent formatting.
"""
import argparse
import difflib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LABS_DIR = REPO_ROOT / "data" / "labs"
DOCS_DIR = REPO_ROOT / "docs" / "labs"

GENERATED_NOTICE = (
    "<!-- AUTO-GENERATED by scripts/gen_lab_docs.py from data/labs/ — do not hand-edit. -->\n"
)

# Hand-authored docs that live under docs/labs/ alongside generated output.
# They are never overwritten and never reported as stale by --check.
HAND_WRITTEN = {"docs/labs/LABSPEC.md"}

# Shipped sample-data reference (fixed template content, not per-lab data):
# describes the gitignored data/samples/ rasters the labs reference by path.
SAMPLE_DATA_TABLE = """\
## 实验数据

所有实验数据位于 `data/samples/` 目录（本地样本栅格，不随仓库分发）：

| 文件 | 说明 | 用途 |
|------|------|------|
| `landsat_sample.tif` | 7波段类Landsat影像 (256×256) | 光谱分析、分类、指数计算 |
| `dem_sample.tif` | 数字高程模型 (256×256) | 地形分析 |
| `change_before.tif` | 变化前影像 | 变化检测 |
| `change_after.tif` | 变化后影像 | 变化检测 |
| `training_samples.shp` | 训练样本ROI | 监督分类 |

### landsat_sample.tif 波段说明
| 波段 | 名称 | 波长范围(μm) | 用途 |
|------|------|-------------|------|
| 1 | Coastal/Aerosol | 0.43-0.45 | 气溶胶检测 |
| 2 | Blue | 0.45-0.51 | 水体、植被 |
| 3 | Green | 0.53-0.59 | 植被健康 |
| 4 | Red | 0.64-0.67 | 植被、土壤 |
| 5 | NIR | 0.85-0.88 | 植被、水体 |
| 6 | SWIR1 | 1.57-1.65 | 土壤、水分 |
| 7 | SWIR2 | 2.11-2.29 | 岩石、土壤 |

### 地物类型
| 类别 | 光谱特征 |
|------|----------|
| 水体 | 各波段反射率低，NIR最低 |
| 植被 | 红光低、NIR高（红边效应） |
| 城市 | 各波段中等反射率 |
| 裸土 | 随波长增加反射率上升 |
| 森林 | 类似植被但NIR更高 |
| 阴影 | 各波段极低反射率 |
"""


def load_labs():
    """All LabSpec documents in stable (file-name) order."""
    return [(p.stem.replace(".lab", ""), json.loads(p.read_text(encoding="utf-8")), p)
            for p in sorted(LABS_DIR.glob("*.lab.json"), key=lambda p: p.name)]


def md_cell(value):
    """Make a scalar safe for a markdown table cell: escape pipes/newlines."""
    return str(value).replace("|", "\\|").replace("\n", " ")


def step_binding_lines(step):
    """Human description of how the step is bound, as markdown lines."""
    lines = []
    if "operator_id" in step:
        lines.append(f"- **绑定算子**：`{step['operator_id']}`")
        params = step.get("params") or {}
        if params:
            lines.append("- **预置参数**：")
            lines.append("")
            lines.append("| 参数 | 值 |")
            lines.append("|------|-----|")
            for key in params:  # document order: authored, deterministic
                value = params[key]
                if isinstance(value, (list, dict)):
                    value = "`" + md_cell(json.dumps(value, ensure_ascii=False)) + "`"
                elif isinstance(value, str):
                    value = "`" + md_cell(value) + "`"
                else:
                    value = md_cell(value)
                lines.append(f"| `{key}` | {value} |")
            lines.append("")
    elif "action" in step:
        lines.append(f"- **界面操作**：主窗口动作 `{step['action']}`")
    else:
        lines.append("- **手动步骤**：无绑定操作")
    return lines


def render_step(index, step):
    out = [f"### 步骤 {index}：{step['title_zh']}（{step['title']}）", ""]
    out.append(step["description_zh"])
    out.append("")
    out += step_binding_lines(step)
    if step.get("teaching_note"):
        out += ["", f"> **原理**：{step['teaching_note']}"]
    if step.get("completion_hint"):
        out += ["", f"✅ **完成标志**：{step['completion_hint']}"]
    out.append("")
    return "\n".join(out)


def render_lab(doc):
    out = [GENERATED_NOTICE, ""]
    out.append(f"# 实验：{doc['title_zh']}（{doc['title']}）")
    out.append("")
    out.append(f"- **实验编号**：`{doc['id']}`")
    out.append("")
    out.append("## 实验目标")
    out.append("")
    out.append(doc["objective"])
    out.append("")
    if doc.get("prerequisites"):
        out.append("## 实验数据")
        out.append("")
        out.append("| 数据 | 说明 |")
        out.append("|------|------|")
        for ref in doc["prerequisites"]:
            out.append(f"| `{ref['path']}` | {md_cell(ref.get('note', ''))} |")
        out.append("")
    out.append("## 实验步骤")
    out.append("")
    for i, step in enumerate(doc["steps"], start=1):
        out.append(render_step(i, step))
    if doc.get("thinking_questions"):
        out.append("## 思考题")
        out.append("")
        for q in doc["thinking_questions"]:
            out.append(f"1. {q}")
        out.append("")
    if doc.get("grading_ref"):
        out.append("## 自动判分")
        out.append("")
        out.append(f"本实验的自动判分管线：`{doc['grading_ref']['pipeline']}`。")
        out.append("")
    return "\n".join(out)


def render_readme(labs):
    out = [GENERATED_NOTICE, ""]
    out.append("# 遥感导论实验指南 — SICNU GEO RS")
    out.append("")
    out.append("本系统为遥感导论本科生实验提供完整的遥感影像处理工作流。")
    out.append("实验由 `data/labs/*.lab.json`（LabSpec）声明式定义：引导式实验面板、")
    out.append("自动判分与本文档均由同一份数据驱动。")
    out.append("")
    out.append("## 实验列表")
    out.append("")
    out.append("| 实验 | 编号 | 步骤 | 绑定算子 |")
    out.append("|------|------|------|----------|")
    for _, doc, _ in labs:
        operators = [s["operator_id"] for s in doc["steps"] if "operator_id" in s]
        out.append(
            f"| [{doc['title_zh']}]({doc['id']}.md) | `{doc['id']}` "
            f"| {len(doc['steps'])} | {len(operators)} |"
        )
    out.append("")
    out.append(SAMPLE_DATA_TABLE)
    out.append("")
    out.append("## LabSpec 创作指南")
    out.append("")
    out.append("参见 [LABSPEC.md](LABSPEC.md) 与 `data/schemas/labspec.schema.json`。")
    out.append("")
    return "\n".join(out)


def build_outputs():
    labs = load_labs()
    outputs = {"docs/labs/README.md": render_readme(labs)}
    for lab_id, doc, _ in labs:
        outputs[f"docs/labs/{lab_id}.md"] = render_lab(doc)
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 when generated output differs from disk")
    args = parser.parse_args()

    if not LABS_DIR.is_dir():
        print(f"error: missing lab directory {LABS_DIR}", file=sys.stderr)
        return 2

    outputs = build_outputs()

    if args.check:
        stale = []
        for rel, generated in sorted(outputs.items()):
            path = REPO_ROOT / rel
            on_disk = path.read_text(encoding="utf-8") if path.exists() else None
            if on_disk != generated:
                stale.append(rel)
                for line in difflib.unified_diff(
                        (on_disk or "").splitlines(), generated.splitlines(),
                        fromfile=rel + " (committed)", tofile=rel + " (generated)", lineterm=""):
                    print(line)
        # Committed docs must contain nothing the generator would not emit
        # (beyond the whitelisted hand-written pages).
        known = {rel for rel in outputs}
        for extra in sorted(DOCS_DIR.glob("*.md")):
            rel = str(extra.relative_to(REPO_ROOT))
            if rel not in known and rel not in HAND_WRITTEN:
                stale.append(rel)
                print(f"--- untracked generated doc (remove): {rel}")
        if stale:
            print(f"error: {len(stale)} generated doc(s) out of sync: {', '.join(stale)}",
                  file=sys.stderr)
            print("run: python3 scripts/gen_lab_docs.py", file=sys.stderr)
            return 1
        print(f"ok: {len(outputs)} generated doc(s) in sync")
        return 0

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    for rel, generated in sorted(outputs.items()):
        (REPO_ROOT / rel).write_text(generated, encoding="utf-8")
    print(f"wrote {len(outputs)} doc(s) under docs/labs/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
