include_guard(GLOBAL)

# Test-harness environment for CTest (#730).
#
# Pins interpreter home, system library search, and Qt IM/plugin isolation so
# the documented `ctest` command is not red for environment reasons:
#   - conda/miniconda RUNPATH shadows system libxml2 (xmlNanoHTTPCleanup)
#   - embedded Python cannot find encodings unless PYTHONHOME matches libpython
#   - fcitx5 platforminputcontext SIGSEGVs at __cxa_finalize after QSS tests
#
# Policy is documented in TEST_INFRA.md. Applied via CTestCustom.cmake (ctest
# process + Catch PRE_TEST discovery), Catch DL_PATHS, and per-test
# ENVIRONMENT_MODIFICATION (see sicnu_register_test_env_applier).

function(_sicnu_escape_cmake_path out_var path)
  string(REPLACE "\\" "\\\\" _esc "${path}")
  string(REPLACE "\"" "\\\"" _esc "${_esc}")
  set(${out_var} "${_esc}" PARENT_SCOPE)
endfunction()

function(sicnu_configure_test_harness_env)
  set(_pythonhome "")
  if(Python_EXECUTABLE)
    execute_process(
      COMMAND "${Python_EXECUTABLE}" -c "import sys; print(sys.base_prefix)"
      OUTPUT_VARIABLE _pythonhome
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET
      RESULT_VARIABLE _pyhome_rc)
    if(NOT _pyhome_rc EQUAL 0)
      set(_pythonhome "")
    endif()
  endif()
  if(NOT _pythonhome AND Python_STDLIB)
    get_filename_component(_py_libdir "${Python_STDLIB}" DIRECTORY)
    get_filename_component(_pythonhome "${_py_libdir}" DIRECTORY)
  endif()

  set(_pypath_parts "")
  foreach(_p IN ITEMS ${Python_STDLIB} ${Python_STDARCH} ${Python_SITELIB})
    if(_p AND NOT _p IN_LIST _pypath_parts)
      list(APPEND _pypath_parts "${_p}")
    endif()
  endforeach()
  if(WIN32)
    set(_pathsep ";")
  else()
    set(_pathsep ":")
  endif()
  string(JOIN "${_pathsep}" _pythonpath ${_pypath_parts})

  set(_qt_plugins "")
  set(_qmake "")
  if(TARGET Qt6::qmake)
    get_target_property(_qmake Qt6::qmake IMPORTED_LOCATION)
  endif()
  if(NOT _qmake)
    find_program(SICNU_TEST_QMAKE NAMES qmake6 qmake-qt6 qmake
      HINTS "${Qt6_DIR}/../../../bin" "${QT6_INSTALL_PREFIX}/bin")
    set(_qmake "${SICNU_TEST_QMAKE}")
  endif()
  if(_qmake)
    execute_process(
      COMMAND "${_qmake}" -query QT_INSTALL_PLUGINS
      OUTPUT_VARIABLE _qt_plugins
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET)
  endif()
  if(NOT _qt_plugins)
    foreach(_cand IN ITEMS
        "/usr/lib/qt6/plugins"
        "/usr/lib/x86_64-linux-gnu/qt6/plugins"
        "/usr/lib64/qt6/plugins")
      if(EXISTS "${_cand}/platforms")
        set(_qt_plugins "${_cand}")
        break()
      endif()
    endforeach()
  endif()

  set(SICNU_TEST_PYTHONHOME "${_pythonhome}" PARENT_SCOPE)
  set(SICNU_TEST_PYTHONPATH "${_pythonpath}" PARENT_SCOPE)
  set(SICNU_TEST_QT_PLUGIN_PATH "${_qt_plugins}" PARENT_SCOPE)
  set(SICNU_TEST_PYTHON_EXECUTABLE "${Python_EXECUTABLE}" PARENT_SCOPE)

  set(_dl_paths "")
  if(UNIX AND NOT APPLE)
    list(APPEND _dl_paths "/usr/lib")
  endif()
  set(SICNU_TEST_DL_PATHS "${_dl_paths}" PARENT_SCOPE)

  # Per-test ENVIRONMENT_MODIFICATION (CMake list of NAME=op:value).
  set(_mods
    "QT_QPA_PLATFORM=set:offscreen"
    "QT_IM_MODULE=set:compose"
    "XMODIFIERS=set:@im=none")
  if(UNIX AND NOT APPLE)
    list(APPEND _mods "LD_LIBRARY_PATH=path_list_prepend:/usr/lib")
  endif()
  if(_pythonhome)
    list(APPEND _mods "PYTHONHOME=set:${_pythonhome}")
  endif()
  if(Python_EXECUTABLE)
    # PythonWorkerProcess prefers /usr/bin/python3; that interpreter is 3.14 on
    # this host while CMake links conda 3.13. Pin the worker to the same
    # executable PYTHONHOME describes.
    list(APPEND _mods "SICNU_PYTHON_EXECUTABLE=set:${Python_EXECUTABLE}")
    list(APPEND _mods "PYTHONEXECUTABLE=set:${Python_EXECUTABLE}")
  endif()
  # Prepend last-path first so the first stdlib entry wins.
  if(_pypath_parts)
    list(REVERSE _pypath_parts)
    foreach(_p IN LISTS _pypath_parts)
      list(APPEND _mods "PYTHONPATH=path_list_prepend:${_p}")
    endforeach()
  endif()
  if(_qt_plugins)
    list(APPEND _mods "QT_PLUGIN_PATH=set:${_qt_plugins}")
  endif()
  set(SICNU_TEST_ENV_MODS "${_mods}" PARENT_SCOPE)

  _sicnu_write_ctest_custom("${_pythonhome}" "${_pythonpath}" "${_qt_plugins}" "${_pathsep}" "${Python_EXECUTABLE}")

  message(STATUS
    "Test harness env (#730): PYTHONHOME=${_pythonhome} "
    "LD_LIBRARY_PATH pin=/usr/lib QT_IM_MODULE=compose")
endfunction()

function(_sicnu_write_ctest_custom pythonhome pythonpath qt_plugins pathsep python_executable)
  _sicnu_escape_cmake_path(_home_esc "${pythonhome}")
  _sicnu_escape_cmake_path(_path_esc "${pythonpath}")
  _sicnu_escape_cmake_path(_qt_esc "${qt_plugins}")
  _sicnu_escape_cmake_path(_pyexe_esc "${python_executable}")

  set(_out "")
  string(APPEND _out
    "# Generated by cmake/SicnuTestEnv.cmake — do not edit.\n"
    "# Policy: TEST_INFRA.md (issue #730).\n"
    "\n"
    "set(ENV{LSAN_OPTIONS} \"detect_leaks=0\")\n"
    "\n"
    "# Offscreen + compose IM. Desktop QT_IM_MODULE=fcitx loads\n"
    "# libfcitx5platforminputcontextplugin.so, which SIGSEGVs in __cxa_finalize\n"
    "# after otherwise-green QSS tests.\n"
    "set(ENV{QT_QPA_PLATFORM} \"offscreen\")\n"
    "set(ENV{QT_IM_MODULE} \"compose\")\n"
    "set(ENV{XMODIFIERS} \"@im=none\")\n")

  if(UNIX AND NOT APPLE)
    string(APPEND _out
      "\n"
      "# System libs first so miniconda on RUNPATH/LD_LIBRARY_PATH cannot shadow\n"
      "# libxml2 (undefined symbol: xmlNanoHTTPCleanup from libspatialite).\n"
      "if(DEFINED ENV{LD_LIBRARY_PATH} AND NOT \"\$ENV{LD_LIBRARY_PATH}\" STREQUAL \"\")\n"
      "  set(ENV{LD_LIBRARY_PATH} \"/usr/lib:\$ENV{LD_LIBRARY_PATH}\")\n"
      "else()\n"
      "  set(ENV{LD_LIBRARY_PATH} \"/usr/lib\")\n"
      "endif()\n")
  endif()

  if(pythonhome)
    string(APPEND _out
      "\n"
      "# Pin embedded/CTest Python to the CMake-discovered interpreter so\n"
      "# encodings is found even under LD_PRELOAD=/usr/lib/libxml2.so or a\n"
      "# stale PYTHONHOME from the shell (e.g. /usr vs conda libpython).\n"
      "set(ENV{PYTHONHOME} \"${_home_esc}\")\n")
    if(python_executable)
      string(APPEND _out
        "set(ENV{SICNU_PYTHON_EXECUTABLE} \"${_pyexe_esc}\")\n"
        "set(ENV{PYTHONEXECUTABLE} \"${_pyexe_esc}\")\n")
    endif()
    if(pythonpath)
      string(APPEND _out
        "if(DEFINED ENV{PYTHONPATH} AND NOT \"\$ENV{PYTHONPATH}\" STREQUAL \"\")\n"
        "  set(ENV{PYTHONPATH} \"${_path_esc}${pathsep}\$ENV{PYTHONPATH}\")\n"
        "else()\n"
        "  set(ENV{PYTHONPATH} \"${_path_esc}\")\n"
        "endif()\n")
    endif()
  endif()

  if(qt_plugins)
    string(APPEND _out
      "\n"
      "# Replace a desktop QT_PLUGIN_PATH so extra IME plugin trees are not\n"
      "# injected. Distro Qt still ships fcitx next to compose; QT_IM_MODULE\n"
      "# selects compose.\n"
      "set(ENV{QT_PLUGIN_PATH} \"${_qt_esc}\")\n")
  endif()

  file(WRITE "${CMAKE_BINARY_DIR}/CTestCustom.cmake" "${_out}")
endfunction()

# Direct add_test() targets (not Catch-discovered). Catch tests get the same
# mods via sicnu_register_test_env_applier at ctest include time.
function(sicnu_set_test_env test_name)
  if(NOT SICNU_TEST_ENV_MODS)
    return()
  endif()
  set_property(TEST "${test_name}" APPEND PROPERTY
    ENVIRONMENT_MODIFICATION ${SICNU_TEST_ENV_MODS})
endfunction()

# Must run after every catch_discover_tests / add_test in this directory so
# the generated include is last in TEST_INCLUDE_FILES. Catch PRE_TEST files
# register tests when ctest includes them; this file then stamps env on all.
function(sicnu_register_test_env_applier)
  set(_file "${CMAKE_CURRENT_BINARY_DIR}/SicnuApplyTestEnv.cmake")
  set(_body "")
  string(APPEND _body
    "# Generated by cmake/SicnuTestEnv.cmake — do not edit.\n"
    "get_property(_sicnu_tests DIRECTORY PROPERTY TESTS)\n"
    "set(_sicnu_mods\n")
  foreach(_m IN LISTS SICNU_TEST_ENV_MODS)
    string(REPLACE "\\" "\\\\" _m_esc "${_m}")
    string(REPLACE "\"" "\\\"" _m_esc "${_m_esc}")
    string(APPEND _body "  \"${_m_esc}\"\n")
  endforeach()
  string(APPEND _body
    ")\n"
    "foreach(_t \${_sicnu_tests})\n"
    "  set_property(TEST \"\${_t}\" APPEND PROPERTY ENVIRONMENT_MODIFICATION \${_sicnu_mods})\n"
    "endforeach()\n")
  file(WRITE "${_file}" "${_body}")
  set_property(DIRECTORY APPEND PROPERTY TEST_INCLUDE_FILES "${_file}")
endfunction()
