/**
 * Track 9 (mcp-surface-r4): pi consumption contract over the SHARED surface
 * snapshot — tests/surface_diff_snapshot.json, generated by
 * tests/surface_snapshot_main.cpp (`ninja -C build-r4 surface_snapshot_regen`)
 * and pinned on the C++ side by tests/test_surface_snapshot.cpp.
 *
 * The shell (exp-rs-spatial.ts) registers exactly the tools/list entries
 * whose family is in EXP_RS_TOOL_CATEGORIES, renamed through piToolName.
 * That consumption path is the third surface of the #1305-family drift
 * triangle: the C++ ends can agree perfectly and pi can still silently
 * stop bridging a renamed family. These tests pin the pi leg against the
 * same file the C++ side pins, with the REAL mapping/truncation functions
 * imported from mcp_bridge.ts (no regex shadow — one source of truth).
 *
 * Run: node --test pi/test/
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  MAX_RESULT_CHARS,
  piToolName,
  toolCategory,
  truncateTail,
} from "../mcp_bridge.ts";

const here = dirname(fileURLToPath(import.meta.url));
const piDir = join(here, "..");
const snapshotPath = join(piDir, "..", "tests", "surface_diff_snapshot.json");
const shellSource = readFileSync(join(piDir, "exp-rs-spatial.ts"), "utf8");

const snapshot = JSON.parse(readFileSync(snapshotPath, "utf8"));
assert.equal(
  snapshot.schemaVersion,
  1,
  "snapshot schemaVersion must be 1 - regenerate: ninja -C build-r4 surface_snapshot_regen",
);
assert.ok(Array.isArray(snapshot.tools) && snapshot.tools.length > 20);

/** The shell's curated families, extracted from the real default (the env
 * override may add opt-in families like rs,gdal,otb — the default is the
 * contract pinned here and by test_surface_parity on the C++ side). */
function defaultCategories() {
  const match = shellSource.match(
    /EXP_RS_TOOL_CATEGORIES\s*\?\?\s*\n?\s*"([^"]+)"/,
  );
  assert.ok(match, "EXP_RS_TOOL_CATEGORIES default not found in the shell");
  return match[1]
    .split(",")
    .map((c) => c.trim().toLowerCase())
    .filter(Boolean);
}

const snapshotFamilies = new Set(snapshot.tools.map((t) => t.family));

test("every default bridged category is a family the snapshot still has", () => {
  // The forbidden drift: a renamed/retired family silently vanishing from
  // the agent surface while the C++ ends stay green.
  for (const category of defaultCategories()) {
    assert.ok(
      snapshotFamilies.has(category),
      `default category '${category}' has no tools in the surface snapshot ` +
        `(regenerate or fix the category list)`,
    );
  }
});

test("every snapshot family is bridged OR explicitly declared unbridged", () => {
  // The reverse gate: when C++ grows a NEW family, the pi side must make a
  // conscious opt-in/opt-out decision - silence (the third drift edge of
  // the triangle: C++ grows, pi never bridges, nobody notices) is a red.
  const intentionallyUnbridged = new Set([
    // processing/operator families: long-running algorithm work stays in
    // the Task Center, discoverable via exprs_search_algorithms (ADR 0122).
    "rs", "gdal", "gdal_tools", "otb", "otb_tools", "qgis", "qgis_algorithms",
    "opencv",
    // GUI-bound interaction surface (headless-hide rule; opt-in via env).
    "view", "roi", "canvas", "layer", "raster",
    // data-platform tables (dataset:/experiment:/reproducibility:/...):
    // platform-governance surfaces, not spatial-intelligence surface.
    "dataset", "experiment", "reproducibility", "benchmark", "scientific",
    // workbench/governance/style families (Platform 3.0/5.0, ADR 0127/0128).
    "workbench", "project", "asset", "collection", "lineage", "result", "run",
    "solution", "style", "template",
    // editing/foundation extras registered in the same registry.
    "editing", "io", "preflight", "recipe", "suitability",
    // RS14-15 why-this-step teaching surface (opt-in, not bridged by default).
    "explain",
  ]);
  const categories = new Set(defaultCategories());
  for (const family of snapshotFamilies) {
    const decided = categories.has(family) || intentionallyUnbridged.has(family);
    assert.ok(
      decided,
      `snapshot family '${family}' is neither bridged by default nor ` +
        `declared intentionally unbridged - decide and update this list`,
    );
  }
});

test("every snapshot tool in a bridged category maps to a unique legal pi name", () => {
  const categories = new Set(defaultCategories());
  const bridged = snapshot.tools.filter((t) => categories.has(toolCategory(t.name)));
  assert.ok(bridged.length > 0, "the bridged slice must not be empty");

  const names = new Set();
  for (const tool of bridged) {
    const piName = piToolName(tool.name);
    assert.match(piName, /^exprs_[a-zA-Z0-9_-]+$/, `${tool.name} -> illegal pi name`);
    assert.ok(
      !names.has(piName),
      `piToolName collision: '${piName}' claimed by more than one MCP tool`,
    );
    names.add(piName);
  }
});

test("the shell's hardcoded tools never collide with a bridged name", () => {
  const hardcoded = [
    ...shellSource.matchAll(/name:\s*"(exprs_[a-zA-Z0-9_-]+)"/g),
  ].map((m) => m[1]);
  assert.ok(hardcoded.includes("exprs_wait_for_execution"));
  assert.ok(hardcoded.includes("exprs_status"));
  const bridged = new Set(snapshot.tools.map((t) => piToolName(t.name)));
  for (const name of hardcoded) {
    assert.ok(
      !bridged.has(name),
      `hardcoded shell tool '${name}' collides with a bridged tools/list name`,
    );
  }
});

test("the shell filters tools/list through the category set (consumption contract)", () => {
  // The uniform tools/list + tools/call path is the only consumption route:
  // filter on the family, register through the bridge, no name forks.
  assert.match(shellSource, /toolCategory\(tool\.name\)/);
  assert.match(shellSource, /categories\.has\(category\)/);
  for (const tool of ["harness:probe_facts", "workflow:run_ir", "cartography:compose"]) {
    assert.doesNotMatch(
      shellSource,
      new RegExp(tool.replace(/:/g, "\\:")),
      `${tool} special-cased in the shell - it must flow through the bridge`,
    );
  }
});

test("snapshot schemas survive a JSON round-trip and keep required ⊆ properties", () => {
  for (const tool of snapshot.tools) {
    const once = JSON.stringify(tool.inputSchema);
    const back = JSON.parse(once);
    assert.deepEqual(back, tool.inputSchema, `${tool.name}: schema wobbles on the wire`);
    if (tool.inputSchema && Array.isArray(tool.inputSchema.required)) {
      const properties = tool.inputSchema.properties ?? {};
      for (const key of tool.inputSchema.required) {
        assert.ok(
          Object.prototype.hasOwnProperty.call(properties, key),
          `${tool.name}: required '${key}' missing from properties`,
        );
      }
    }
  }
});

test("truncateTail keeps the tail and announces the cut (never a silent drop)", () => {
  assert.equal(truncateTail("short"), "short");
  const long = "x".repeat(MAX_RESULT_CHARS + 777);
  const marked = truncateTail(long);
  assert.ok(
    marked.includes("777 characters truncated, tail kept"),
    `marker must announce the dropped count, got: ${marked.slice(0, 80)}`,
  );
  // Tail kept: the result ENDS with the original tail, capped at the budget.
  assert.ok(marked.length <= MAX_RESULT_CHARS + 80);
  assert.ok(long.endsWith(marked.slice(marked.indexOf("…]\n") + 3).slice(0, 50)));
});
