/***************************************************************************
 * rs_majority_filter_operator.h  —  3x3 Majority filter RSOperator
 ***************************************************************************/
#pragma once

#include "operators/framework/rs_operator.h"

namespace sicnu::operators::rs {

/**
 * Applies a 3x3 majority (mode) sliding window filter to a classification label raster
 * to reduce salt-and-pepper noise while preserving class boundaries.
 *
 * Parameters:
 *   input   (string, required) Input single-band label raster path
 *   output  (string, optional) Output label raster path (autogenerated if omitted)
 *   kernel  (int, optional)    Odd kernel size >= 3 (default: 3)
 *
 * Returns JSON object with:
 *   output  (string) Output raster path
 */
class RsMajorityFilterOperator : public RSOperator {
public:
    std::string name() const override { return "rs:majority_filter"; }
    std::string displayName() const override { return "3x3 Majority Filter"; }
    std::string determinismGrade() const override { return "bit-exact"; } // #659 (ADR 0124)
    std::string group() const override { return "classification"; }
    std::string description() const override {
        return "Apply a majority sliding-window filter to a classification raster to reduce noise.";
    }

    Json::Value schema() const override;
    Json::Value metadata() const override;
    Json::Value executionEstimate() const override;
    RSOperatorMemoryPolicy memoryPolicy() const override
    {
        return RSOperatorMemoryPolicy::Streaming; // halo row-block streaming (#666)
    }

    Json::Value run(const Json::Value& params, RSOperatorContext& context) override;
};

} // namespace sicnu::operators::rs
