/***************************************************************************
 * rs_recode_operator.h  —  Class recode RSOperator
 ***************************************************************************/
#pragma once

#include "operators/framework/rs_operator.h"

namespace sicnu::operators::rs {

/**
 * Remaps integer class labels according to a recode mapping dictionary.
 *
 * Parameters:
 *   input       (string, required) Input single-band label raster path
 *   output      (string, optional) Output label raster path (autogenerated if omitted)
 *   recode_map  (object/string, optional) Key-value map of {from_class_id: to_class_id}
 *   map         (object/string, optional) Alias for recode_map
 *
 * Returns JSON object with:
 *   output      (string) Output raster path
 */
class RsRecodeOperator : public RSOperator {
public:
    std::string name() const override { return "rs:recode"; }
    std::string displayName() const override { return "Class Recode"; }
    std::string group() const override { return "classification"; }
    std::string description() const override {
        return "Remap integer class labels according to a recode mapping table.";
    }

    Json::Value schema() const override;
    Json::Value metadata() const override;
    Json::Value run(const Json::Value& params, RSOperatorContext& context) override;
};

} // namespace sicnu::operators::rs
